<?php

use Drupal\custom_node_models\Model\NodeArticle;
use Drupal\custom_node_models\Model\NodePage;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function custom_node_models_entity_bundle_info_alter(&$bundles): void {
  if (isset($bundles['node']['article'])) {
    $bundles['node']['article']['class'] = NodeArticle::class;
  }
  if (isset($bundles['node']['page'])) {
    $bundles['node']['page']['class'] = NodePage::class;
  }
}
